<!DOCTYPE html>
<html>
<head>
  <title>Geek de Montagne, votre guide dans les Alpes</title>
  <meta charset="utf-8">
  <link href="vues/assets/css/bootstrap.css" rel="stylesheet"/>
  <link rel="stylesheet" href="vues/style.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <?php include 'include/header.php' ?> 

  <?php include 'include/menu.php' ?> 

</br>
<p>    	 


  <?php
  echo' ICI ON TROUVE LE CORPS DE LA PAGE ACCUEIL';
      //PostModel->afficherNews();
  ?>



</p>

<?php include 'include/footer.php' ?> 
</body>

</html>