<!DOCTYPE html>
<html>
<head>
  <title>Geek de Montagne, votre guide dans les Alpes</title>
  <meta charset="utf-8">
  <link href="vues/assets/css/bootstrap.css" rel="stylesheet"/>
  <link rel="stylesheet" href="vues/style.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <?php include 'include/header.php' ?> 
  <?php include 'include/menu.php' ?> 
</br>

<!-- Zone pour ajouter la news -->
    <FORM method="post" action="index.php?page=add">
    <label>Votre pseudo</label> : </br><input type="text" name="auteur" required/></br>
    <label>Votre titre</label> : </br><input type="text" name="titre" size="50" required /></br>
    <label>Votre chapo</label> :</br> <TEXTAREA name="chapo" rows=5 cols=200 wrap=physical placeholder="Rédiger le chapo ici" required /></TEXTAREA></br>
    <label>Votre article</label> :</br> <TEXTAREA name="contenu" rows=20 cols=200 wrap=physical placeholder="Rédiger votre news ici" required  /></TEXTAREA></br>
    <INPUT TYPE="submit" NAME="ajouterNews" VALUE=" Envoyer ">
    </FORM>
<?php include 'include/footer.php' ?> 
</body>

</html>